"""Typed agent artifact schemas for NEXUS Multi-Agent Orchestration.

This module defines strongly typed, dataclass/Pydantic-compatible artifact schemas
used for structured communication between specialized AI agents.

Core Truth Boundary Invariant:
Every model-generated artifact MUST preserve:
  reality = "INFERRED"
  untrusted = True
No model or agent is allowed to promote model-generated claims to OBSERVED or VERIFIED.
Agents exchange structured artifacts rather than unrestricted conversational state.
"""
from __future__ import annotations

from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
import json
from typing import Any, ClassVar, Type
import uuid


def utc_now() -> str:
    """Return current UTC timestamp in ISO 8601 format."""
    return datetime.now(timezone.utc).isoformat()


def generate_artifact_id(prefix: str = "art") -> str:
    """Generate a unique identifier with a given prefix."""
    return f"{prefix}-{uuid.uuid4().hex[:12]}"


class ArtifactValidationError(ValueError):
    """Raised when an artifact fails schema, invariant, or truth-boundary validation."""
    pass


ROLE_PLANNER = "planner"
ROLE_IMPLEMENTER = "implementer"
ROLE_TEST_AUTHOR = "test_author"
ROLE_REVIEWER = "reviewer"
ROLE_SECURITY_REVIEWER = "security_reviewer"
ROLE_VERIFIER = "verifier"
ROLE_DEBUGGER = "debugger"
ROLE_SANDBOX = "sandbox_runner"

VALID_ROLES = {
    ROLE_PLANNER,
    ROLE_IMPLEMENTER,
    ROLE_TEST_AUTHOR,
    ROLE_REVIEWER,
    ROLE_SECURITY_REVIEWER,
    ROLE_VERIFIER,
    ROLE_DEBUGGER,
    ROLE_SANDBOX,
}


@dataclass
class AgentArtifact:
    """Base artifact with provenance, identity, and truth-boundary tracking."""
    task_id: str
    agent_role: str = ""
    artifact_id: str = field(default_factory=lambda: generate_artifact_id("art"))
    provider: str = "unknown"
    model: str = "unknown"
    timestamp: str = field(default_factory=utc_now)
    parent_artifact_id: str | None = None
    status: str = "SUCCESS"
    reasoning: str = ""
    evidence_references: list[str] = field(default_factory=list)
    reality: str = "INFERRED"
    untrusted: bool = True
    model_generated: bool = True
    artifact_type: str = "base"

    def __post_init__(self) -> None:
        # Strict NEXUS Truth Boundary Invariant:
        # Model-generated artifacts are ALWAYS INFERRED and untrusted.
        if self.model_generated:
            self.reality = "INFERRED"
            self.untrusted = True

        if not self.task_id or not isinstance(self.task_id, str):
            raise ArtifactValidationError("Artifact task_id must be a non-empty string")
        if not self.agent_role or self.agent_role not in VALID_ROLES:
            raise ArtifactValidationError(f"Invalid agent_role '{self.agent_role}'. Valid roles: {sorted(VALID_ROLES)}")

    def to_dict(self) -> dict[str, Any]:
        """Convert artifact to a JSON-serializable dictionary."""
        return asdict(self)

    def to_json(self, indent: int | None = None) -> str:
        """Serialize artifact to a JSON string."""
        return json.dumps(self.to_dict(), indent=indent)

    def validate(self) -> None:
        """Validate artifact integrity and invariant rules."""
        if self.model_generated:
            if self.reality != "INFERRED":
                raise ArtifactValidationError(
                    f"Truth boundary violation: model-generated artifact cannot have reality='{self.reality}'"
                )
            if not self.untrusted:
                raise ArtifactValidationError(
                    "Truth boundary violation: model-generated artifact cannot have untrusted=False"
                )


@dataclass
class PlanArtifact(AgentArtifact):
    """Decomposed implementation plan generated by PlannerAgent."""
    objective: str = ""
    target_files: list[str] = field(default_factory=list)
    steps: list[str] = field(default_factory=list)
    acceptance_criteria: list[str] = field(default_factory=list)
    risk_assessment: str = ""

    def __post_init__(self) -> None:
        self.artifact_type = "plan"
        self.agent_role = ROLE_PLANNER
        self.model_generated = True
        super().__post_init__()
        if not self.objective:
            raise ArtifactValidationError("PlanArtifact requires a non-empty objective")

    def validate(self) -> None:
        super().validate()
        if not self.objective:
            raise ArtifactValidationError("PlanArtifact objective cannot be empty")
        if not self.steps:
            raise ArtifactValidationError("PlanArtifact requires at least one execution step")


@dataclass
class PatchArtifact(AgentArtifact):
    """Candidate code changes and commit description generated by ImplementerAgent."""
    files: dict[str, str] = field(default_factory=dict)  # relative_path -> new/modified content
    commit_message: str = ""
    rationale: str = ""
    modified_files: list[str] = field(default_factory=list)
    diffs: dict[str, str] = field(default_factory=dict)

    def __post_init__(self) -> None:
        self.artifact_type = "patch"
        self.agent_role = ROLE_IMPLEMENTER
        self.model_generated = True
        super().__post_init__()
        if not self.modified_files and self.files:
            self.modified_files = list(self.files.keys())

    def validate(self) -> None:
        super().validate()
        if not self.files:
            raise ArtifactValidationError("PatchArtifact files dictionary cannot be empty")


@dataclass
class TestSuiteArtifact(AgentArtifact):
    """Deterministic test suite generated by TestAuthorAgent."""

    # This is a domain artifact named after a test *suite*, not a pytest test
    # case. Without this, pytest tries to collect it as a test class and warns.
    __test__ = False

    test_files: dict[str, str] = field(default_factory=dict)  # relative_path -> test file content
    framework: str = "unittest"  # "unittest", "pytest"
    target_modules: list[str] = field(default_factory=list)

    def __post_init__(self) -> None:
        self.artifact_type = "test_suite"
        self.agent_role = ROLE_TEST_AUTHOR
        self.model_generated = True
        super().__post_init__()

    def validate(self) -> None:
        super().validate()
        if not self.test_files:
            raise ArtifactValidationError("TestSuiteArtifact test_files dictionary cannot be empty")


@dataclass
class ReviewArtifact(AgentArtifact):
    """Code quality, architecture, and convention review generated by ReviewerAgent."""
    approved: bool = False
    score: int = 0  # 1 to 10
    comments: list[str] = field(default_factory=list)
    required_changes: list[str] = field(default_factory=list)
    syntax_ok: bool = True

    def __post_init__(self) -> None:
        self.artifact_type = "review"
        self.agent_role = ROLE_REVIEWER
        self.model_generated = True
        super().__post_init__()
        if not (1 <= self.score <= 10) and self.score != 0:
            raise ArtifactValidationError(f"ReviewArtifact score must be between 1 and 10, got {self.score}")

    def validate(self) -> None:
        super().validate()
        if not (1 <= self.score <= 10):
            raise ArtifactValidationError(f"Review score must be between 1 and 10, got {self.score}")


@dataclass
class SecurityAuditArtifact(AgentArtifact):
    """Security audit evaluating secrets, dangerous calls, and injection risks."""
    passed: bool = False
    secret_findings: list[str] = field(default_factory=list)
    dangerous_calls: list[str] = field(default_factory=list)
    prompt_injections_detected: list[str] = field(default_factory=list)
    risk_level: str = "LOW"  # "LOW", "MEDIUM", "HIGH", "CRITICAL"

    def __post_init__(self) -> None:
        self.artifact_type = "security_audit"
        self.agent_role = ROLE_SECURITY_REVIEWER
        self.model_generated = True
        super().__post_init__()
        valid_risks = {"LOW", "MEDIUM", "HIGH", "CRITICAL"}
        if self.risk_level not in valid_risks:
            raise ArtifactValidationError(f"Invalid risk_level '{self.risk_level}'. Valid: {sorted(valid_risks)}")

    def validate(self) -> None:
        super().validate()
        if self.secret_findings and self.passed:
            raise ArtifactValidationError("Security audit cannot pass with active secret findings")
        if self.dangerous_calls and self.passed:
            raise ArtifactValidationError("Security audit cannot pass with unresolved dangerous calls")


@dataclass
class ExecutionResultArtifact(AgentArtifact):
    """Deterministic output from test execution in sandbox runner (Phase 3)."""
    exit_code: int = -1
    stdout: str = ""
    stderr: str = ""
    tests_run: int = 0
    tests_passed: int = 0
    tests_failed: int = 0
    duration_seconds: float = 0.0
    command: str = ""

    def __post_init__(self) -> None:
        self.artifact_type = "execution_result"
        if not self.agent_role:
            self.agent_role = ROLE_SANDBOX
        # Execution result from deterministic runner can reflect observed reality
        # if explicitly marked as not model_generated
        if self.model_generated:
            self.reality = "INFERRED"
            self.untrusted = True
        else:
            self.reality = "OBSERVED"
            self.untrusted = False
        super().__post_init__()

    def validate(self) -> None:
        if self.model_generated:
            super().validate()
        if self.exit_code == 0 and self.tests_failed > 0:
            raise ArtifactValidationError("Contradiction: exit_code is 0 but tests_failed > 0")


@dataclass
class DiagnosticArtifact(AgentArtifact):
    """Failure diagnostics and root cause analysis generated by DebuggerAgent."""
    root_cause: str = ""
    suggested_fix: str = ""
    target_file: str = ""
    error_type: str = ""
    failure_context: str = ""
    attempt_number: int = 1

    def __post_init__(self) -> None:
        self.artifact_type = "diagnostic"
        self.agent_role = ROLE_DEBUGGER
        self.model_generated = True
        super().__post_init__()
        if not self.root_cause:
            raise ArtifactValidationError("DiagnosticArtifact requires a non-empty root_cause")

    def validate(self) -> None:
        super().validate()
        if not self.root_cause:
            raise ArtifactValidationError("DiagnosticArtifact root_cause cannot be empty")


@dataclass
class VerificationArtifact(AgentArtifact):
    """Final independent verification outcome."""
    status: str = "PENDING"  # "VERIFIED", "FAILED", "PENDING"
    passed: bool = False
    independent: bool = True
    checks: dict[str, bool] = field(default_factory=dict)
    evidence_ids: list[str] = field(default_factory=list)
    summary: str = ""

    def __post_init__(self) -> None:
        self.artifact_type = "verification"
        self.agent_role = ROLE_VERIFIER
        # Truth boundary invariant: An agent's statement alone is model-generated
        # and therefore INFERRED and untrusted.
        if self.model_generated:
            self.reality = "INFERRED"
            self.untrusted = True
        super().__post_init__()
        valid_statuses = {"VERIFIED", "FAILED", "PENDING"}
        if self.status not in valid_statuses:
            raise ArtifactValidationError(f"Invalid verification status '{self.status}'. Valid: {sorted(valid_statuses)}")

    def validate(self) -> None:
        super().validate()
        if self.status == "VERIFIED" and not self.passed:
            raise ArtifactValidationError("Contradiction: status is 'VERIFIED' but passed is False")
        if self.passed and self.status != "VERIFIED":
            raise ArtifactValidationError("Contradiction: passed is True but status is not 'VERIFIED'")


ARTIFACT_TYPE_MAP: dict[str, Type[AgentArtifact]] = {
    "base": AgentArtifact,
    "plan": PlanArtifact,
    "patch": PatchArtifact,
    "test_suite": TestSuiteArtifact,
    "review": ReviewArtifact,
    "security_audit": SecurityAuditArtifact,
    "execution_result": ExecutionResultArtifact,
    "diagnostic": DiagnosticArtifact,
    "verification": VerificationArtifact,
}


def artifact_from_dict(data: dict[str, Any]) -> AgentArtifact:
    """Reconstruct a typed artifact from a dictionary using its artifact_type."""
    if not isinstance(data, dict):
        raise ArtifactValidationError("Input data must be a dictionary")
    artifact_type = data.get("artifact_type", "base")
    cls = ARTIFACT_TYPE_MAP.get(artifact_type)
    if cls is None:
        raise ArtifactValidationError(f"Unknown artifact_type '{artifact_type}'")

    # Create shallow copy to avoid mutating source
    kwargs = dict(data)
    # Instantiate typed artifact
    try:
        return cls(**kwargs)
    except TypeError as exc:
        raise ArtifactValidationError(f"Failed to instantiate {cls.__name__}: {exc}") from exc


def artifact_from_json(json_str: str) -> AgentArtifact:
    """Deserialize a typed artifact from a JSON string."""
    try:
        data = json.loads(json_str)
    except json.JSONDecodeError as exc:
        raise ArtifactValidationError(f"Invalid JSON string: {exc}") from exc
    return artifact_from_dict(data)
